#!/bin/bash

# recieve new apt keys
function addkeys {
    keys_added=false
    while read F
    do
        EX=$(apt-key list | grep -w $F)
        if [ "" == $EX ]
        then
            show_info 'adding keys ... ' $(cat $KEYS)
            sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys $(cat $KEYS)
            keys_added=true
        fi
    done < $KEYS
    # clang from apt.llvm.org
    wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
    if $keys_added
    then
        sudo apt-get update
        show_success 'apt keys added'
    fi
}

# add new apt repositories
function addrepos {
    repos_added=false
    while read F
    do
        REX=grep "$F" /etc/apt/sources.list
        if [ "" == "$REX" ]
        then
            show_info 'adding repos ... ' "$(cat $REPOS)"
            sudo add-apt-repository "$F"
            repos_added=true
        fi
    done < $REPOS

    if $repos_added
    then
        sudo apt-get update
        sudo apt-get upgrade
        show_success 'apt repositories added'
    fi
}

# Install packages listed in 'data/packages.list'
function addapt {
    if (eval `resize` && whiptail \
        --title "Apt Repositories" \
        --yesno "apt keys to recieve: \n\n$(cat $KEYS) \n\nRepositories to add: \n\n$(cat $REPOS)" \
        $LINES $COLUMNS $(( $LINES - 12 )) \
        --scrolltext) then
        show_info 'Installing...'
        show_warning 'Requires root privileges'
        addkeys
        addrepos

        # Done
        show_success 'Done.'
        # Check
        EXITSTATUS=$1
        if [[ $EXITSTATUS != 0 ]]; then
            # Already installed
            show_success 'Already installed.'
            whiptail --title "Finished" --msgbox "apt keys and repositories added." 8 78
            main
        else
            whiptail --title "Finished" --msgbox "Installation complete." 8 78
            main
        fi
    else
        main
    fi
}
