#!/bin/bash

source $DIR/functions/non-apt/instvim
source $DIR/functions/non-apt/instpandoc
source $DIR/functions/non-apt/instpython
source $DIR/functions/non-apt/sourcecodepro
source $DIR/functions/non-apt/travis
source $DIR/functions/non-apt/rpackages

# Install packages listed in 'data/packages.list'
function doall {
    if (eval `resize` && whiptail \
        --title "Everything" \
        --yesno "Install and setup whole system non-interactively?" \
        $LINES $COLUMNS $(( $LINES - 12 )) \
        --scrolltext) then

        # ---aptadd
        #addkeys
        #addrepos

        # ---packages
        #while read F ; do
        #    if $(dpkg-query -l $F | grep "no packages")
        #    then
        #        sudo apt-get install -y $F
        #    else
        #        echo "package "$F" already installed"
        #    fi
        #done < $PKGS
        #sudo R CMD javareconf
        #gdal

        # ---nonapt
        set_preferences

        # ---non-apt/instvim
        install_vim_core
        pathogen
        solarized
        # ---non-apt/pandoc
        install_pandoc_core
        # ---non-apt/sourcecodepro
        install_sourcecodepro
        # ---non-apt/travis
        sudo apt-get install ruby-dev
        sudo gem install travis --no-rdoc --no-ri
        # ---non-apt/rpackages
        if [ -d "$RLIBLOC" ]; then
            while read F ; do
                CMD='install.packages('\"$F\"',repos='\"$CRAN\"',lib.loc='\"$RLIBLOC\"')'
                echo sudo Rscript --verbose -e $CMD
            done < $RPKGS
        else
            while read F ; do
                CMD='install.packages('\"$F\"',repos='\"$CRAN\"')'
                sudo Rscript --verbose -e $CMD
            done < $RPKGS
        fi
        # ---non-apt/python
        install_python

        # Done
        show_success 'Done.'
        main
    else
        main
    fi
}
