#!/bin/bash

dir="$(dirname "$0")"

source $dir/functions/non-apt/vim
source $dir/functions/non-apt/pandoc
source $dir/functions/non-apt/sourcecodepro
source $dir/functions/non-apt/travis

# Install non-apt packages
function nonapt {
    eval `resize`
    NONAPT=$(whiptail \
        --notags \
        --title "non-apt packages" \
        --menu "\nWhat non-apt packages would you like to install/update?" \
        --ok-button "Install/Update" \
        --cancel-button "Go Back" \
        $LINES $COLUMNS $(( $LINES - 12 )) \
        'vim'           '1. vim' \
        'pandoc'        '2. pandoc' \
        'sourcecodepro' '3. Source Code Pro' \
        'travis'        '4. travis-ci client' \
        3>&1 1>&2 2>&3)
     
    exitstatus=$?
    if [ $exitstatus = 0 ]; then
        $NONAPT
    else
        main
    fi
}
