#!/bin/bash

echo "-----$DIR-----"

. $DIR/functions/non-apt/instvim
. $DIR/functions/non-apt/instdropbox
. $DIR/functions/non-apt/instpandoc
. $DIR/functions/non-apt/instpython
. $DIR/functions/non-apt/sourcecodepro
. $DIR/functions/non-apt/travis
. $DIR/functions/non-apt/rpackages

# Install non-apt packages
function nonapt {
    eval `resize`
    NONAPT=$(whiptail \
        --notags \
        --title "non-apt packages" \
        --menu "\nWhat non-apt packages would you like to install/update?" \
        --ok-button "Install/Update" \
        --cancel-button "Go Back" \
        $LINES $COLUMNS $(( $LINES - 12 )) \
        'install_vim'       '1. vim' \
        'install_pandoc'    '2. pandoc' \
        'install_python'    '3. python' \
        'sourcecodepro'     '4. Source Code Pro' \
        'travis'            '5. travis-ci client' \
        'rpackages'         '6. R packages' \
        3>&1 1>&2 2>&3)
     
    exitstatus=$?
    if [ $exitstatus = 0 ]; then
        $NONAPT
    else
        main
    fi
}
