#!/bin/bash

dir="$(dirname "$0")"

PKGS="$dir/data/packages.list"

# Install packages listed in 'data/packages.list'
function packages {
    if (eval `resize` && whiptail \
        --title "Packages" \
        --yesno "Current list of packages to install: \n\n$(cat $PKGS) \n\nProceed with installation?" \
        $LINES $COLUMNS $(( $LINES - 12 )) \
        --scrolltext) then
        show_info 'Installing...'
        show_warning 'Requires root privileges'
        sudo apt-get install -y $(cat $PKGS)
        sudo R CMD javareconf
        # Done
        show_success 'Done.'
        # Check
        EXITSTATUS=$1
        if [[ $EXITSTATUS != 0 ]]; then
            # Already installed
            show_success 'Already installed.'
            whiptail --title "Finished" --msgbox "Packages are already installed." 8 78
            main
        else
            whiptail --title "Finished" --msgbox "Installation complete." 8 78
            main
        fi
    else
        main
    fi
}
