#!/bin/bash

DIR="$(dirname "$0")"

PKGS="$DIR/data/packages.list"

function gdal_install {
    GDAL_URL="http://download.osgeo.org/gdal/CURRENT/"
    wget -O temp.html $GDAL_URL
    GDAL_VERSION=`cat temp.html | grep -o -P '(?<=gdal-).*(?=.tar.gz\")'`
    GDAL_FILE="gdal-"$GDAL_VERSION".tar.gz"
    rm temp.html
    wget $GDAL_URL$GDAL_FILE
    tar zxf $GDAL_FILE
    cd "gdal-"$GDAL_VERSION
    ./configure
    make
    sudo make install
    cd ..
    rm -rf "gdal-"$GDAL_VERSION $GDAL_FILE
}

function gdal {
    GNAME="GDAL"
    if hash gdalinfo 2>/dev/null; then
        show_info "GDAL installed"
        VERS=$(eval "gdalinfo --version" | head -n 2 | cut -d " " -f 2)
        MAJOR=$(echo $VERS | cut -d "." -f 1)
        MINOR=$(echo $VERS | cut -d "." -f 1)
        if [ $MAJOR -lt 2 ]; then
            if (whiptail --title $GNAME --yesno "$GNAME version < 2; upgrade?." 8 78) then
                gdal_install
            fi
        fi
    else
        if (whiptail --title $GNAME --yesno "$GNAME not installed; install?." 8 78) then
            gdal_install
        fi
    fi
}

# Install packages listed in 'data/packages.list'
function packages {
    if (eval `resize` && whiptail \
        --title "Packages" \
        --yesno "Current list of packages to install: \n\n$(cat $PKGS) \n\nProceed with installation?" \
        $LINES $COLUMNS $(( $LINES - 12 )) \
        --scrolltext) then
        show_info 'Installing...'
        show_warning 'Requires root privileges'
        #sudo apt-get install -y $(cat $PKGS)
        while read F ; do
            if $(dpkg-query -l $F | grep "no packages")
            then
                sudo apt-get install -y $F
            else
                echo "package "$F" already installed"
            fi
        done < $PKGS
        sudo R CMD javareconf

        gdal

        # Done
        show_success 'Done.'
        # Check
        EXITSTATUS=$1
        if [[ $EXITSTATUS != 0 ]]; then
            # Already installed
            show_success 'Already installed.'
            whiptail --title "Finished" --msgbox "All packages already installed." 8 78
            main
        else
            whiptail --title "Finished" --msgbox "Installation complete." 8 78
            main
        fi
    else
        main
    fi
}
