#!/bin/bash

function install_pandoc {
    URL=$(curl -s https://api.github.com/repos/jgm/pandoc/releases | \
        grep browser_download_url | head -n 1 | cut -d '"' -f 4)
    sudo wget $URL
    show_header 'installing '$NAME' ...'
    file=${URL#https://github.com/jgm/pandoc/releases/download/}
    file=${file#*/}
    sudo dpkg -i $file
    # Cleanup and finish
    rm -rf $file
}

# pandoc - not complete coz lacks version comparison
function pandoc {
	# Variables
	PACKAGE=pandoc
	NAME="pandoc"
    PKGCHECK=$(dpkg-query -W --showformat='${Status}\n' $PACKAGE|grep "install ok installed")
    if [ "" == "$PKGCHECK" ]; then
        INST_UPDATE="installation"
        INST_UPDATE_VERB="Installing"
    else
        INST_UPDATE="update"
        INST_UPDATE_VERB="Updating"
    fi
	# Install
	show_header 'Begin '$NAME' '$INST_UPDATE
    install_pandoc
    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "$INST_UPDATE_VERB $NAME complete." 8 78
    nonapt
}
