#!/bin/bash

# R
function R {
	# Variables
	NAME="R"	
	show_header 'Begin '$NAME' installation'
	# Check if already installed
	echo 'Checking if '$NAME' is already installed...'
    PKGCHECK=$(dpkg-query -W --showformat='${Status}\n' $PACKAGE|grep "install ok installed")
    if [ "" == "$PKGCHECK" ]; then
        echo $NAME 'is not installed. Proceeding'
		# Add the repository signing key to be able to verify downloaded packages
		show_info 'Adding '$NAME' signing key to keyring...'
		show_warning 'Requires root privileges'
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
		show_success 'Done.'
		# Add the repository
		show_info 'Adding '$NAME' repository to software sources...'
		show_warning 'Requires root privileges'
        sudo add-apt-repository "deb http://cran.r-project.org/bin/linux/ubuntu xenial/"
		# Update repository information
		show_info 'Updating repository information...'
		sudo apt-get update -y
	    show_success 'Done.'
		# Install
		show_info 'Installing '$NAME'...'
		sudo apt-get install r-base r-base-dev
		show_success 'Done.'
	    whiptail --title "Finished" --msgbox "Installation of $NAME complete." 8 78
		nonapt
    else
        # Already installed
        show_success $NAME 'already installed.'
	    whiptail --title "Finished" --msgbox "$NAME is already installed." 8 78
	    nonapt
    fi
}
