#!/bin/bash

function tcolorbox {
    TCNAME="tcolorbox"
    URL="http://mirrors.ctan.org/install/macros/latex/contrib/tcolorbox.tds.zip"
    show_header 'Downloading '$TCNAME
    sudo wget $URL
    unzip "tcolorbox.tds.zip" -d "tcolorbox"
    sudo cp -rf tcolorbox/tex/latex/tcolorbox/ /usr/share/texlive/texmf-dist/tex/latex/tcolorbox/
    rm -rf tcolorbox tcolorbox.tds.zip
}
