#!/bin/bash

function pathogen {
    FILE=$HOME"/.vim/autoload/pathogen.vim"
    PNAME="pathogen"
    if [ ! -e $FILE ]; then
        show_info 'installing '$PNAME
        mkdir -p ~/.vim/autoload ~/.vim/bundle && \
            curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim
    else
        whiptail --title $PNAME --msgbox "$PNAME already installed." 8 78
        show_info $PNAME' already installed'
    fi
}

function solarized {
    PFILE=$HOME"/.vim/autoload/pathogen.vim"
    if [ ! -e $FILE ]; then
        pathogen
        show_info 'installing '$PNAME
    fi
    SDIR=$HOME"/.vim/bundle/vim-colors-solarized/"
    SNAME="vim-colors-solarized"
    if [ -d $DIR ]; then
        whiptail --title $SNAME --msgbox "$SNAME already installed." 8 78
        show_info "$SNAME already installed."
    else
        show_info "Installing "$SNAME
        pwd=$PWD
        cd $HOME/.vim/bundle
        git clone https://github.com/altercation/vim-colors-solarized.git
        cd vim-colors-solarized
        mv vim-colors-solarized $HOME/.vim/bundle
        cd $PWD
    fi
}

# vim
function vim {
	# Variables
	PACKAGE=vim
	NAME="vim"
    PKGCHECK=$(dpkg-query -W --showformat='${Status}\n' $PACKAGE|grep "install ok installed")
    if [ "" == "$PKGCHECK" ]; then
        INST_UPDATE="installation"
        INST_UPDATE_VERB="Installing"
    else
        INST_UPDATE="update"
        INST_UPDATE_VERB="Updating"
    fi
    if (whiptail --title "vim" --yesno "Begin $NAME $INST_UPDATE?" 8 78) then
        # Install
        show_header 'Begin '$NAME' '$INST_UPDATE
        # Install git if not installed
        GITCHECK=$(dpkg-query -W --showformat='${Status}\n' git|grep "install ok installed")
        if [ "" == "$PKGCHECK" ]; then
            echo 'installing git first ...'
            sudo apt-get install git
        fi
        # Clone git repo
        git clone https://github.com/vim/vim.git
        # Install package(s)
        show_info $INST_UPDATE_VERB' '$NAME'...'
        show_warning 'Requires root privileges'
        cd vim/src
        make distclean
        make
        sudo make install
        # Cleanup and finish
        cd ../..
        rm -rf vim
    fi

    pathogen
    solarized

    # Done
    show_success 'Done.'
    whiptail --title "Finished" --msgbox "$INST_UPDATE_VERB $NAME complete." 8 78
    nonapt
}
